### ISSUE TITLE
Provide environment vairables to tests

### ISSUE THREAD

**Issue by Rookfighter** [build2-packaging/nng#2]
Hi @boris-kolpackov,

so far this packages looks good, everything is compiling. However most of the time the tests fail, due to race conditions. The tests are executed in parallel (not sure if this is coming from build2 or NNG), but the tests use sockets internally which causes them to race for the socket ports (address already in use is the fail reason [see here](https://ci.stage.build2.org/@9516d765-d42b-44cd-82d4-1fafe7ff98f7)). In the upstream project, each test executeable is provided with a separate port via an environment variable `TEST_PORT`. Can I somehow provide each test executable with a different value for the same environment variable (preferably in a cross-platform way). E.g. something like this:

```
exe{foo_test}: test.env += TEST_PORT="12345"
exe{bar_test}: test.env += TEST_PORT="54321"
```

A more general question: Is there a way in build2 how I can "explore" for example the `test` namespace (not sure what's the correct term here) for executables? I mean printing the whole tree of `exe{*}: test` would be sufficient for me.

For example I wanted to configure a timeout on a per test basis. I found out that there is a `config.test.timeout =200/10`config option (doumented [here](https://build2.org/build2/doc/build2-build-system-manual.xhtml#module-test)), but  transferring this on a per test basis did not work out.

```
exe{foo_test}: test.timeout = /10
exe{bar_test}: test.timeout = /20
```

**Comment by boris-kolpackov** [comment]
> Can I somehow provide each test executable with a different value for the same environment variable (preferably in a cross-platform way). 

Yes, you can do it from a `testscript`: https://build2.org/build2/doc/build2-testscript-manual.xhtml#builtins-env

> A more general question: Is there a way in build2 how I can "explore" for example the `test` namespace (not sure what's the correct term here) for executables? I mean printing the whole tree of `exe{*}: test` would be sufficient for me.

No, there is no such feature, but could probably be added.

> For example I wanted to configure a timeout on a per test basis. I found out that there is a `config.test.timeout` [...]

No, this variable specified the timeout for the `test` operation, not for individual tests: https://build2.org/build2/doc/build2-build-system-manual.xhtml#module-test

But that `env` builtin that allows you to specify test environment also allows you to specify timeout. There is also related `timeout` builtin: https://build2.org/build2/doc/build2-testscript-manual.xhtml#builtins-timeout

**Comment by boris-kolpackov** [comment]
BTW, you could also achieve the same with an ad hoc recipe:

```
exe{hello}: {hxx ixx txx cxx}{**} $libs
% [diag=test] test
{{
  env FOO=BAR -- $> 'World' >>>?'Hello, World!'
}}
```

**Comment by Rookfighter** [comment]
Thanks, I wasn't even aware of `testscript` :+1:
